"""empty message

Revision ID: 183cn3ere3il
Revises: c832ne8ce132
Create Date: 2021-07-23 11:22:16.933475

"""
from alembic import op
from app.models.co_op import CoOpModel
from app.models.role import RoleModel
from datetime import datetime, timedelta


# revision identifiers, used by Alembic.
revision = '183cn3ere3il'
down_revision = 'c832ne8ce132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.bulk_insert(CoOpModel.__table__,
    [   
        {
            'co_op_id': 1,
            'name':'CoOp A',
            'start_date': datetime.now(),
            'end_date': datetime.now() + timedelta(days = 365*5),
            'location': 'Seattle',
            'inital_balance': 20000,
            'current_balance': 20000
        }
   ])

    op.bulk_insert(RoleModel.__table__,
    [
        {
            'role_id': 1,
            'name': 'Admin'
        },
        {
            'role_id': 2,
            'name': 'Leader'
        },
        {
            'role_id': 3,
            'name': 'Member'
        }
    ])
    # ### end Alembic commands ###
